"""Write docs/results_ps26086.md from the outlook result files (rerun after any retrain: every number comes from JSON).

  python scripts/report_ps26086.py
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RES = REPO / "outlook" / "results"
cv = json.load(open(RES / "cv_metrics.json"))
sel = json.load(open(RES / "final_selection.json"))
hv3 = json.load(open(RES / "stack_week1_metrics.json"))
hgfs = json.load(open(RES / "stack_metrics.json"))
hgefs = json.load(open(RES / "stack_gefs_metrics.json")) if (RES / "stack_gefs_metrics.json").exists() else {}
hgefs2 = json.load(open(RES / "stack_gefs2_metrics.json")) if (RES / "stack_gefs2_metrics.json").exists() else {}
hblend = json.load(open(RES / "stack_blend_metrics.json")) if (RES / "stack_blend_metrics.json").exists() else {}
hens = json.load(open(RES / "stack_ens_metrics.json")) if (RES / "stack_ens_metrics.json").exists() else {}

NAME = {"dry": "Dry week (all 7 days < 2.5 mm)", "wet": "Wet week (≥ 1.5 × normal)", "heavy": "Heavy rain (a day ≥ 30 mm)",
        "onset": "Monsoon onset in that week", "break3w": "Dry spell ≥ 7 days within 3 weeks", "false3w": "False onset within 3 weeks"}
SRC = {"outlook": "climate-driver outlook", "v3": "outlook + v3 week 1", "gfs": "outlook + GFS d1–16 + v3 week 1",
       "gefs": "outlook + GEFS 11-member ensemble", "gefs2": "outlook + calibrated GEFS ensemble",
       "blend": "mean of GFS and calibrated-GEFS hybrids", "v3ens": "outlook + v3 diffusion ensemble"}


def label(t):
    if t in ("break3w", "false3w"):
        return NAME[t]
    e, k = t.rsplit("_", 1)
    return f"{NAME[e]}, week {k}"


def ci(c):
    return f"[{c[0]:+.3f}, {c[1]:+.3f}]"


def hy(h, t):
    c = h.get(t)
    return f"{c['bss_stacked']:+.3f} {ci(c['ci90_stacked'])}" if c else "–"


rows = []
for t in cv:
    s = sel[t]
    o = hgefs2.get(t, {}).get("ops_test")
    ops = f"{o['bss_outlook']:+.3f} → {o['bss_stacked']:+.3f}" if o else "–"
    rows.append(f"| {label(t)} | {cv[t]['base_rate']:.3f} | {cv[t]['bss']:+.3f} {ci(cv[t]['ci90'])} | {hy(hv3, t)} | {hy(hens, t)} | {hy(hgfs, t)} | "
                f"{hy(hgefs, t)} | {hy(hgefs2, t)} | {hy(hblend, t)} | {ops} | **{SRC[s['source']]}** | **{s['bss']:+.3f}** |")
n_skill = sum(1 for t in sel if sel[t]["ci90"][0] > 0)
relf = RES / "reliability_shipped.json"
rel = json.load(open(relf)) if relf.exists() else {}


def rel_note(r):
    over = [b_ for b_ in r["bins"] if b_[0] - b_[1] > 0.08 and b_[2] > 5000]
    under = [b_ for b_ in r["bins"] if b_[1] - b_[0] > 0.08 and b_[2] > 5000]
    if over and under:
        return f"underconfident near {under[0][0]:.2f}, overconfident near {over[0][0]:.2f}"
    if over:
        return f"overconfident above {min(b_[0] for b_ in over):.2f}"
    if under:
        return f"underconfident near {under[0][0]:.2f}"
    return "well calibrated"


rel_rows = "\n".join(f"| {label(t)} | {SRC[r['source']]} | {r['ece'] * 100:.1f}% | {r['n']:,} | {rel_note(r)} |" for t, r in rel.items())
gfs_seasons = next(iter(hgfs.values()))["seasons"]
gefs_seasons = next(iter(hgefs.values()))["seasons"] if hgefs else "–"

md = f"""# PS 26086 — Hyperlocal monsoon onset & break outlook: results

Every number below is generated by `scripts/report_ps26086.py` from `outlook/results/*.json`.

## What the system forecasts
Per gram panchayat (234 GPs, Mandya district), issued every day from 1 May to 30 September, probabilities for weeks 1–4:

| Event | Definition |
|---|---|
| dry_k | all 7 days of week k < 2.5 mm (IMD dry day) |
| wet_k | week-k total ≥ 1.5 × the panchayat's normal for that week (normal from training seasons only) |
| heavy_k | any day of week k ≥ 30 mm |
| onset_k | agronomic onset falls in week k: first 2-day rain ≥ 20 mm from 25 May not followed by a 7-day spell < 5 mm within 20 days |
| break3w | a run of ≥ 7 dry days inside the next 21 days |
| false3w | sowing rains followed by such a dry spell, within the next 21 days |

Observed truth: CHIRPS v2.0 0.05° daily rain, 1981–2023, area-weighted to each GP polygon.

## Models
1. **Sub-seasonal outlook** (18 models, one per event × lead): regularised logistic regression on climatology, recent rain
   (7/30 days, dry days, season anomaly, wet starts), real-time MJO (NOAA ROMI), BSISO (real-time PCs), ENSO (weekly Niño 3.4,
   ≥ 4 days old), IOD (previous month's DMI), calendar and location, with MJO/BSISO × season interactions. Onset and false
   onset use a lean 9-feature logistic (the full set overfits these rare events).
2. **Hybrids**: logistic stackers that add numerical forecasts to the outlook probability:
   * **GEFS (weeks 1–4):** the NOAA GEFSv12 11-member ensemble, days 1–28 from the latest 35-day run. Inputs per week are the ensemble-mean total and the fraction of members with a dry week, a heavy day and a sowing-rain start, plus the fraction with a ≥ 7-day dry run.
   * **GFS (weeks 1–2):** the GFS 0.25° forecast for days 1–16: weekly totals, wettest 2 days and dry days.
   * **v3 (week 1):** the v3 deep downscaling model's week-1 forecast.
3. **Expert system**: thresholded rules turn the shipped probabilities into ranked advisories in Kannada and English
   (`outlook/advisory.py`).

## Validation
* Outlook: 9 season-blocked folds over 43 seasons. Each season is predicted by models that never saw it, and climatology comes from the same training folds.
* Hybrids: leave-one-season-out over the seasons with forecast archives, on top of outlook probabilities that are themselves out-of-fold.
  * GEFS: {gefs_seasons}, using the NOAA reforecasts. Every issue day uses the latest Wednesday 35-day run, 0–6 days old. That is conservative, because operational GEFS runs to 35 days every day.
  * GFS: {gfs_seasons}.
  * v3: 9 seasons, 2015–2023.
* **Independent operational test (GEFS):** the GEFS stacker trained on 2000–2019 reforecasts is applied unchanged to the real operational GEFS forecasts of 2021–2023, which it never saw. The "ops test" column shows outlook → hybrid (v2) Brier skill on those seasons. 2020 is excluded because GEFS then ran only 16 days.
* Score: Brier skill score (BSS) vs climatology (0 = no better than the long-term average). 90 % CI from a season bootstrap.
* **Selection rule (fixed before the final run):** a hybrid replaces the outlook only if, on its own validation rows, its BSS beats the outlook's AND its 90 % CI lower bound is above zero. If several hybrids qualify, the one with the largest gain over the outlook wins. Candidates are validated on different seasons, so raw BSS values are not comparable; this tie-break was fixed before any GEFS result was seen (`outlook/select.py`).

## Skill

| Target | Base rate | Outlook, 43 seasons | + v3 week 1 | + v3 diffusion ensemble | + GFS d1–16 + v3 | + GEFS v1 | + GEFS v2 (calibrated) | GFS/GEFS-v2 average | GEFS v2 ops test 2021–23 | Shipped | Shipped BSS |
|---|---|---|---|---|---|---|---|---|---|---|---|
{chr(10).join(rows)}

**{n_skill} of {len(sel)}** shipped targets have a 90 % CI entirely above zero.

### Reading the table
* **Clear skill:**
  * Dry and wet weeks in weeks 1–2, and dry-spell (break) risk, through the GFS hybrid.
  * Dry weeks in weeks 3–4 from the climate drivers, mainly the MJO and BSISO.
* **No reliable skill:**
  * Heavy-rain days beyond what climatology gives.
  * Onset week, except a small signal in week 4.
  * For these targets the system ships calibrated climatology-like probabilities.
  * Heavy-rain advisories are therefore capped at amber; red is reserved for events with validated skill.
* **Validation sample:** the hybrids rest on fewer seasons than the outlook (8–20 vs 43), so their CIs are wider.

### What the GEFS ensemble added
**v1** is a generic 19-input stacker on raw GEFS.
* Over 20 reforecast seasons it improves dry weeks 1–3, wet week 1 and dry-spell risk.
* On rare events it does worse than the outlook, and its dry-week-3 gain did not hold up in the operational test.

**v2** changes three things, all fixed before its results were seen:
* **Calibration:** GEFS rain is quantile-mapped to observed panchayat rain. Raw GEFS averages rain over ~25 km boxes, so it rarely shows a heavy day.
* **Event-matched inputs:** each event's own definition (dry week, wet week, heavy day, onset, false start, dry spell) is applied to every one of the 11 member trajectories.
* **A lean stacker:** the outlook's logit is a fixed offset, so the stacker only learns corrections, using the target's own 2–5 inputs.

**Results:**
* v2 lifts dry week 3 to +0.077 and dry week 4 to +0.055.
  * Both 90% ranges are above zero.
  * Both gains hold up in the operational test on 2021–2023, which the model never saw.
* Averaging the GFS and calibrated-GEFS hybrids, with no fitting, gives the largest gain over the outlook for dry weeks 1–2 and dry-spell risk on 8 seasons.
  * The rule therefore ships the average for those three targets.
  * Its raw BSS on its own seasons can look lower than the GFS hybrid's on different seasons. The comparison that counts is gain over the outlook on the same rows.

**No validated gain:** heavy-rain days and onset in weeks 1–3.
* Calibrated member onset fractions move onset weeks 1–2 slightly positive (+0.006, +0.012), but their 90% ranges still include zero, so they are not shipped.
* This is consistent with the known limits of sub-seasonal rainfall prediction. Beyond week 2, village-scale skill comes mainly from the MJO/BSISO state and the dry/wet tendency, not from day-to-day rain amounts.

### What the v3 diffusion ensemble added
* **Setup:** each season 2015–2022 got a residual denoiser trained without that season, on top of out-of-fold backbone forecasts; 2023 uses the shipped denoiser, which never saw it.
  * Every season has 16 members, all out-of-sample (5 Kaggle GPU runs, about 6 GPU-hours).
* **Wet week 1:** the ensemble improves it the most of any model (+0.088 → +0.225 on the same rows), so the rule ships it there.
* **Dry week 1:** it improves (+0.124 → +0.156), but less than the GFS/GEFS average.
* **Heavy rain week 1:** it does **not** gain reliably (+0.019, 90% range [−0.069, +0.086]).
  * The members' wettest-day intensity carries the signal; the fraction of members with a ≥ 30 mm day adds nothing.
  * Village-scale downpours are not predictable a week ahead with this sample of 9 seasons.

## Reliability of what ships
The data comes from `outlook.reliability`, on each forecast's own validation rows. The calibration gap is the row-weighted mean distance between forecast probability and observed frequency, over 10 bins.

| Target | Model used | Calibration gap | Rows | Note |
|---|---|---|---|---|
{rel_rows}

## Leakage audits (all fixed before the numbers above)
| Issue | Effect | Fix |
|---|---|---|
| OMI MJO index uses a centred 20–96-day filter (future days) | leaks the coming weeks into the issue date | real-time ROMI (causal) |
| break3w counted dry runs that began before the issue date | BSS 0.99 on synthetic data | runs counted inside the window only |
| onset triggered by pre-monsoon showers (median 18 May) | onset targets meaningless | onset search starts 25 May |
| replay marked onset as "seen" on its date, though confirming it needs 21 later days | advisory state used up to 3 weeks of future rain | onset counts only from day d+22 |
| feature causality | – | test: changing all rain from the issue day on leaves features bit-identical |

Overall skill moved by mixed amounts after the MJO fix, because BSISO was added in the same retrain. No published number depends on the leaky index.

## Data caveats
* **GFS 2015–2020:** from the NCAR RDA archive (6-h mean rates).
  * In FV3-era files (mid-2019 onward), days 11–16 keep only a 6-hour mean rate at 12-hourly steps. Their 12-h totals are approximated as that rate × 12 h.
  * A few inits are missing (2015: 4, 2016: 2, 2017: 1). On those days the hybrid falls back to the outlook.
* **v3 week-1 forecasts:** out-of-fold, June–September only. In May the v3 hybrid is not used.
* **BSISO:** the real-time PCs cover 2002-03 to 2022-12. Missing values are flagged and handled by the model.
* **CHIRPS:** satellite-plus-gauge rain, not IMD station truth. It was used because it is consistent over 43 seasons at 0.05°.
* **Kannada advisories:** need review by a native-speaking agronomist before field use.

## How to run
```
python -m outlook.build <chirps_dir> outlook/data/idx      # GP rain + indices
python -m outlook.model                                      # 18 outlook models, CV metrics, final models
python -m outlook.stack_v3 && python -m outlook.stack_v3 final
python outlook/merge_gfs16.py && python -m outlook.stack_gfs ckpts/gfs16/all 0.005
python -m outlook.stack_gefs ckpts/gefs                      # GEFS v1 (reforecast + operational, kaggle/gefs)
python -m outlook.stack_gefs2 ckpts/gefs                     # GEFS v2 (calibrated) + GFS/GEFS average
python -m outlook.stack_ens ckpts/ens                        # v3 diffusion ensemble, out-of-fold (kaggle runs ens-*)
python -m outlook.select                                     # final_selection.json
python -m outlook.issue 2023-06-12 --out issue.json          # operational outlook for one date
python -m monsoon.build_bundle --source real                 # web app data
```
"""
(REPO / "docs" / "results_ps26086.md").write_text(md, encoding="utf-8")
print("wrote docs/results_ps26086.md", n_skill, "/", len(sel), "skilful")
