"""Write docs/results_ps26086.md from the outlook result files (rerun after any retrain: every number comes from JSON).

  python scripts/report_ps26086.py
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RES = REPO / "outlook" / "results"
cv = json.load(open(RES / "cv_metrics.json"))
sel = json.load(open(RES / "final_selection.json"))
hv3 = json.load(open(RES / "stack_week1_metrics.json"))
hgfs = json.load(open(RES / "stack_metrics.json"))
hgefs = json.load(open(RES / "stack_gefs_metrics.json")) if (RES / "stack_gefs_metrics.json").exists() else {}

NAME = {"dry": "Dry week (all 7 days < 2.5 mm)", "wet": "Wet week (≥ 1.5 × normal)", "heavy": "Heavy rain (a day ≥ 30 mm)",
        "onset": "Monsoon onset in that week", "break3w": "Dry spell ≥ 7 days within 3 weeks", "false3w": "False onset within 3 weeks"}
SRC = {"outlook": "climate-driver outlook", "v3": "outlook + v3 week 1", "gfs": "outlook + GFS d1–16 + v3 week 1",
       "gefs": "outlook + GEFS 11-member ensemble"}


def label(t):
    if t in ("break3w", "false3w"):
        return NAME[t]
    e, k = t.rsplit("_", 1)
    return f"{NAME[e]}, week {k}"


def ci(c):
    return f"[{c[0]:+.3f}, {c[1]:+.3f}]"


def hy(h, t):
    c = h.get(t)
    return f"{c['bss_stacked']:+.3f} {ci(c['ci90_stacked'])}" if c else "–"


rows = []
for t in cv:
    s = sel[t]
    o = hgefs.get(t, {}).get("ops_test")
    ops = f"{o['bss_outlook']:+.3f} → {o['bss_stacked']:+.3f}" if o else "–"
    rows.append(f"| {label(t)} | {cv[t]['base_rate']:.3f} | {cv[t]['bss']:+.3f} {ci(cv[t]['ci90'])} | {hy(hv3, t)} | {hy(hgfs, t)} | "
                f"{hy(hgefs, t)} | {ops} | **{SRC[s['source']]}** | **{s['bss']:+.3f}** |")
n_skill = sum(1 for t in sel if sel[t]["ci90"][0] > 0)
gfs_seasons = next(iter(hgfs.values()))["seasons"]
gefs_seasons = next(iter(hgefs.values()))["seasons"] if hgefs else "–"

md = f"""# PS 26086 — Hyperlocal monsoon onset & break outlook: results

Every number below is generated by `scripts/report_ps26086.py` from `outlook/results/*.json`.

## What the system forecasts
Per gram panchayat (234 GPs, Mandya district), issued every day from 1 May to 30 September, probabilities for weeks 1–4:

| Event | Definition |
|---|---|
| dry_k | all 7 days of week k < 2.5 mm (IMD dry day) |
| wet_k | week-k total ≥ 1.5 × the panchayat's normal for that week (normal from training seasons only) |
| heavy_k | any day of week k ≥ 30 mm |
| onset_k | agronomic onset falls in week k: first 2-day rain ≥ 20 mm from 25 May not followed by a 7-day spell < 5 mm within 20 days |
| break3w | a run of ≥ 7 dry days inside the next 21 days |
| false3w | sowing rains followed by such a dry spell, within the next 21 days |

Observed truth: CHIRPS v2.0 0.05° daily rain, 1981–2023, area-weighted to each GP polygon.

## Models
1. **Sub-seasonal outlook** (18 models, one per event × lead): regularised logistic regression on climatology, recent rain
   (7/30 days, dry days, season anomaly, wet starts), real-time MJO (NOAA ROMI), BSISO (real-time PCs), ENSO (weekly Niño 3.4,
   ≥ 4 days old), IOD (previous month's DMI), calendar and location, with MJO/BSISO × season interactions. Onset and false
   onset use a lean 9-feature logistic (the full set overfits these rare events).
2. **Hybrids**: logistic stackers that add numerical forecasts to the outlook probability:
   * **GEFS (weeks 1–4):** the NOAA GEFSv12 11-member ensemble, days 1–28 from the latest 35-day run. Inputs per week are the ensemble-mean total and the fraction of members with a dry week, a heavy day and a sowing-rain start, plus the fraction with a ≥ 7-day dry run.
   * **GFS (weeks 1–2):** the GFS 0.25° forecast for days 1–16: weekly totals, wettest 2 days and dry days.
   * **v3 (week 1):** the v3 deep downscaling model's week-1 forecast.
3. **Expert system**: thresholded rules turn the shipped probabilities into ranked advisories in Kannada and English
   (`outlook/advisory.py`).

## Validation
* Outlook: 9 season-blocked folds over 43 seasons. Each season is predicted by models that never saw it, and climatology comes from the same training folds.
* Hybrids: leave-one-season-out over the seasons with forecast archives, on top of outlook probabilities that are themselves out-of-fold.
  * GEFS: {gefs_seasons}, using the NOAA reforecasts. Every issue day uses the latest Wednesday 35-day run, 0–6 days old. That is conservative, because operational GEFS runs to 35 days every day.
  * GFS: {gfs_seasons}.
  * v3: 9 seasons, 2015–2023.
* **Independent operational test (GEFS):** the GEFS stacker trained on 2000–2019 reforecasts is applied unchanged to the real operational GEFS forecasts of 2021–2023, which it never saw. The "ops test" column shows outlook → hybrid Brier skill on those seasons. 2020 is excluded because GEFS then ran only 16 days.
* Score: Brier skill score (BSS) vs climatology (0 = no better than the long-term average). 90 % CI from a season bootstrap.
* **Selection rule (fixed before the final run):** a hybrid replaces the outlook only if, on its own validation rows, its BSS beats the outlook's AND its 90 % CI lower bound is above zero. If several hybrids qualify, the one with the largest gain over the outlook wins. Candidates are validated on different seasons, so raw BSS values are not comparable; this tie-break was fixed before any GEFS result was seen (`outlook/select.py`).

## Skill

| Target | Base rate | Outlook, 43 seasons | + v3 week 1 | + GFS d1–16 + v3 | + GEFS ensemble | GEFS ops test 2021–23 | Shipped | Shipped BSS |
|---|---|---|---|---|---|---|---|---|
{chr(10).join(rows)}

**{n_skill} of {len(sel)}** shipped targets have a 90 % CI entirely above zero.

### Reading the table
* **Clear skill:**
  * Dry and wet weeks in weeks 1–2, and dry-spell (break) risk, through the GFS hybrid.
  * Dry weeks in weeks 3–4 from the climate drivers, mainly the MJO and BSISO.
* **No reliable skill:**
  * Heavy-rain days beyond what climatology gives.
  * Onset week, except a small signal in week 4.
  * For these targets the system ships calibrated climatology-like probabilities.
  * Heavy-rain advisories are therefore capped at amber; red is reserved for events with validated skill.
* **Validation sample:** the hybrid rows rest on far fewer seasons (≤ 9) than the outlook (43), so their CIs are wider.

### What the GEFS ensemble added
* **Reforecasts (20 seasons, 2000–2019):** the GEFS hybrid improves dry weeks 1–3, wet week 1 and dry-spell risk.
  * The GFS hybrid gains more on the targets both cover, so under the selection rule GEFS replaces the outlook only for dry week 3.
  * It does not help heavy rain at weeks 3–4 or onset; on some of these rare events it is worse than the outlook.
* **Operational test (2021–2023):** the reforecast-trained stacker, applied unchanged, keeps or improves its gains for weeks 1–2 and dry spells.
  * Dry week 3 does not improve in this test (only 3 seasons), so that selection rests on the 20 reforecast seasons alone.
* **Interpretation:** these results are consistent with the known limits of sub-seasonal rainfall prediction. Skill beyond week 2 at village scale comes mainly from the MJO/BSISO state and the dry/wet tendency, not from day-to-day rain amounts.

## Leakage audits (all fixed before the numbers above)
| Issue | Effect | Fix |
|---|---|---|
| OMI MJO index uses a centred 20–96-day filter (future days) | leaks the coming weeks into the issue date | real-time ROMI (causal) |
| break3w counted dry runs that began before the issue date | BSS 0.99 on synthetic data | runs counted inside the window only |
| onset triggered by pre-monsoon showers (median 18 May) | onset targets meaningless | onset search starts 25 May |
| replay marked onset as "seen" on its date, though confirming it needs 21 later days | advisory state used up to 3 weeks of future rain | onset counts only from day d+22 |
| feature causality | – | test: changing all rain from the issue day on leaves features bit-identical |

Overall skill moved by mixed amounts after the MJO fix, because BSISO was added in the same retrain. No published number depends on the leaky index.

## Data caveats
* **GFS 2015–2020:** from the NCAR RDA archive (6-h mean rates).
  * In FV3-era files (mid-2019 onward), days 11–16 keep only a 6-hour mean rate at 12-hourly steps. Their 12-h totals are approximated as that rate × 12 h.
  * A few inits are missing (2015: 4, 2016: 2, 2017: 1). On those days the hybrid falls back to the outlook.
* **v3 week-1 forecasts:** out-of-fold, June–September only. In May the v3 hybrid is not used.
* **BSISO:** the real-time PCs cover 2002-03 to 2022-12. Missing values are flagged and handled by the model.
* **CHIRPS:** satellite-plus-gauge rain, not IMD station truth. It was used because it is consistent over 43 seasons at 0.05°.
* **Kannada advisories:** need review by a native-speaking agronomist before field use.

## How to run
```
python -m outlook.build <chirps_dir> outlook/data/idx      # GP rain + indices
python -m outlook.model                                      # 18 outlook models, CV metrics, final models
python -m outlook.stack_v3 && python -m outlook.stack_v3 final
python outlook/merge_gfs16.py && python -m outlook.stack_gfs ckpts/gfs16/all 0.005
python -m outlook.stack_gefs ckpts/gefs                      # GEFS reforecast + operational (kaggle/gefs)
python -m outlook.select                                     # final_selection.json
python -m outlook.issue 2023-06-12 --out issue.json          # operational outlook for one date
python -m monsoon.build_bundle --source real                 # web app data
```
"""
(REPO / "docs" / "results_ps26086.md").write_text(md, encoding="utf-8")
print("wrote docs/results_ps26086.md", n_skill, "/", len(sel), "skilful")
